### ISSUE TITLE
Limit TensorFlow to the number of real cores available to the container

### ISSUE THREAD

**Issue by superbobry** [criteo/tf-yarn#13]
Currently, TensorFlow could try to use all cores available on the node (the [exact logic](https://github.com/tensorflow/tensorflow/blob/52574f95279d8cd5ec22cfc24668b9586e41367a/tensorflow/core/platform/posix/port.cc#L53) is a bit more involved). We might want instead to limit it to the number of *real* cores allocated for the container. This will make the application slower on empty nodes, but potentially faster (this should be verified) alongside other compute-heave applications.

**Comment by superbobry** [comment]
AFAIK this should be sufficient.

**Comment by hamidmaei** [comment]
Thanks, so I'll add it and the will do PR.

**Comment by fhoering** [comment]
Can be done by tuning intra_op_parallelism_threads & .inter_op_parallelism_threads. for the moment we prefer not to put any default values in there and leave it up to the user. When we have issure with too many jobs consuming too many resources we will see again.
