### ISSUE TITLE
Limit maximum JVM heap size for libhdfs

### ISSUE THREAD

**Issue by superbobry** [criteo/tf-yarn#14]
libhdfs relies on the JVM defaults for calculating min/max size (-Xms, -Xmx) which could be unreasonable for the case of a JNI-invoked JVM in a shared cluster environment (e.g. the max size gets as high as 28G on 256G nodes). We might want to fix the heap size explicitly by [setting](https://www.cloudera.com/documentation/enterprise/5-9-x/topics/cdh_ig_hdfs_mountable.html#cdh_ig_hdfs_mountable_opt) `LIBHDFS_OPTS`.

/cc @ashangit

**Comment by ashangit** [comment]
I think that on // to this issue we can also set some default setting on the cluster on this env variable (LIBHDFS_OPTS="-Xms64m -Xmx256m”, perhaps with bigger Xmx)

**Comment by fhoering** [comment]
Done with
https://github.com/criteo/tf-yarn/commit/00455e4a7a1cc82f80301dd4c41cbe198340b482
