### ISSUE TITLE
Recovering from task failures

### ISSUE THREAD

**Issue by superbobry** [criteo/tf-yarn#15]
Currently, tf-yarn does not support any kind of error recovery and stops the whole application if at least one of tasks fails. Bellow are some vague ideas on how to address this.

### try-except

The simplest and the easiest to implement option is just restarting the training thread once it fails. 

Pros:
* trivial to implement,
* no need to re-allocate container and re-init the cluster,
* works for all failures which result in Python exceptions.

Cons: 
* does not cover all possible scenarios, specifically, does not work in case of a segfault or TF going above YARN resource limits;
* requires [`SO_REUSEPORT`](tensorflow/tensorflow/issues/21492) in order to ensure that another application does not hijack the port used by the TF master service;
* relies on `tf.train.Server` releasing the TCP socket after the failure (not sure if this is the case).

### Re-*

Another option is to let Skein restart the container (assuming [`max_restarts`](https://jcrist.github.io/skein/api.html#skein.Service) is non-zero).

Pros:
* covers all possible failure scenarios.

Cons:
* requires extra care to recover task ID after the restart (see jcrist/skein#64),
* requires to [propagate](https://github.com/tensorflow/tensorflow/issues/18880#issuecomment-385523892) the new socket address through the cluster.

### ?

**Comment by jdlesage** [comment]
I prefer the second option. In this case,  about to configure tensorflow to restart from the last checkpoint?

**Comment by superbobry** [comment]
IIUC attempting to recover from a checkpoint is the default behaviour of the [`MonitoredTrainingSession`](https://www.tensorflow.org/api_docs/python/tf/train/MonitoredTrainingSession) used by `tf.estimator.train_and_evaluate`.

**Comment by jdlesage** [comment]
To be checked if a restart option in skein

**Comment by fhoering** [comment]
Done with:
https://github.com/criteo/tf-yarn/commit/89609a435c3e8e2dcb2604d69ad0182e873191b6

Will retry from latest checkpoint in the model path
