### ISSUE TITLE
PS container status is always succeeded in final status report

### ISSUE THREAD

**Issue by fhoering** [criteo/tf-yarn#17]
We use the event mechanism for displaying the status of each container and not the yarn container status.
In the case of the PS we shave a special handling and send the stop event at the beginning of the container run. Therefore, the PS containers are always considered as succeeded even if it fails later.
We should find a way to get the real status of the yarn container

**Comment by superbobry** [comment]
Do you mean that if the thread running the parameter server raises an exception it would not be propagated to the edge node? I think we could emit a second stop/ event with an exception in this case. It should override the `stop/ = ""`.

**Comment by fhoering** [comment]
Won't fix
