### ISSUE TITLE
Migrate to human-readable memory specs

### ISSUE THREAD

**Issue by superbobry** [criteo/tf-yarn#24]
This mostly concerns the tutorial and examples. 2**XX should be swapped for human-readable strings once a new version of Skein (with jcrist/skein#87) is out.

**Comment by jcrist** [comment]
This was part of version 0.3.0 (latest release is 0.5.0), and should be doable now.

**Comment by fhoering** [comment]
Done with:
https://github.com/criteo/tf-yarn/commit/35386628581cc600eb46da53e07c4465b87bad1c
