### ISSUE TITLE
Add support for CollectiveAllReduceStrategy (add in tf 1.11)

### ISSUE THREAD

**Issue by fhoering** [criteo/tf-yarn#25]
Tf 1.11 implemented CollectiveAllReduceStrategy to have a gradiant all-reduce without parameter servers (in-graph replication with synchronous training on many GPUs on one machine, brings in fault tolerance when workers fail & might improve performance)

https://github.com/tensorflow/tensorflow/blob/r1.11/tensorflow/contrib/distribute/README.md
https://www.tensorflow.org/api_docs/python/tf/contrib/distribute/CollectiveAllReduceStrategy

Requires updating tensorflow to 1.11

Code sample on how to activate:
```
estimator = ...
  distribution = tf.contrib.distribute.CollectiveAllReduceStrategy(
      num_gpus_per_worker=2)
  config = tf.estimator.RunConfig(train_distribute=distribution)
  train_spec = tf.estimator.TrainSpec(input_fn=input_fn)
  eval_spec = tf.estimator.EvalSpec(input_fn=eval_input_fn)
  tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
```

**Comment by fhoering** [comment]
We have made some tests and fixes to be able to run without PS.
It works with a basic model with only numerical columns. Unfortunately it doesn't work when the model uses categorical columns.
Tracked in: https://github.com/tensorflow/tensorflow/issues/24003

**Comment by hamidmaei** [comment]
> We have made some tests and fixes to be able to run without PS.
> It works with a basic model with only numerical columns. Unfortunately it doesn't work when the model uses categorical columns.
> Tracked in: [tensorflow/tensorflow#24003](https://github.com/tensorflow/tensorflow/issues/24003)

thanks @fhoering for pointing this out. It looks like it is an important problem as in most cases in industry the data has a huge categorical elements into it.

**Comment by fhoering** [comment]
Closed with this [fix](https://github.com/criteo/tf-yarn/commit/10d3497892c7d0c6890585b990d4b511bb5fe62d). Supported by tf-yarn but there are still some [limitations](https://github.com/tensorflow/tensorflow/blob/r1.13/tensorflow/contrib/distribute/README.md#caveats) on tf side (Also see https://github.com/tensorflow/tensorflow/issues/24003)
