### ISSUE TITLE
Failed on first install

### ISSUE THREAD

**Issue by kyauaa** [criteo/tf-yarn#27]
I try to start this project, however I found an error when I first install.

#:~/tfyarn/tf-yarn$ pip install .
Processing /home/jay/tfyarn/tf-yarn
Collecting tensorflow==1.11.0.criteo (from tf-yarn===0.1.2.criteo)
  Could not find a version that satisfies the requirement tensorflow==1.11.0.criteo (from tf-yarn===0.1.2.criteo) (from versions: 0.12.1, 1.0.0, 1.0.1, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.2.0rc0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.4.1, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.5.1, 1.6.0rc0, 1.6.0rc1, 1.6.0, 1.7.0rc0, 1.7.0rc1, 1.7.0, 1.7.1, 1.8.0rc0, 1.8.0rc1, 1.8.0, 1.9.0rc0, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0rc0, 1.10.0rc1, 1.10.0, 1.10.1, 1.11.0rc0, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.12.0rc0, 1.12.0rc1, 1.12.0rc2)
No matching distribution found for tensorflow==1.11.0.criteo (from tf-yarn===0.1.2.criteo)

Did I miss any requirement ?

**Comment by kyauaa** [comment]
I have checked that TARGET_ENVIRONMENT is not set, but it still shows the same error.

**Comment by jdlesage** [comment]
@kyauaa. Closing this ticket. Do not hesitate to reopen this issue if it didn't solve your case.
