### ISSUE TITLE
Update for changes in Skein 0.5.0

### ISSUE THREAD

**Issue by jcrist** [criteo/tf-yarn#30]
I just released a new version of Skein that deprecates a few things (hopefully smoothly). You may need to update your code accordingly:

- The `commands` field has been deprecated in favor of `script`, where `script` is the full text of a bash script to run the service.
- The `daemon` has been renamed to `driver` since this was confusing for some users. Things like `skein.Client.from_global_daemon` should be renamed to `skein.Client.from_global_driver`.

You also may be interested in the added ability to run user code directly on the application master. Fields like `script`, `env`, `files`, etc... can now be passed to `skein.Master`, just as they can to `skein.Service`. In addition, when this user process exits the whole application will be shutdown cleanly (with `final_status` determined by the exit code). Since many applications are managed by a single driving process (spark's driver, dask's client, etc...), this can make writing applications that match this model easier (they'll also startup faster). See [here](https://jcrist.github.io/skein/specification.html#specification-master) for more information.

The full changelog is [here](https://jcrist.github.io/skein/changelog.html#version-0-5-0-january-7-2019).

**Comment by fhoering** [comment]
Thanks @jcrist 
We will probably use this to span Tensorboard in the AppMaster instead of a separate container.

**Comment by jcrist** [comment]
Version 0.6.0 has just been released, which removes the deprecated functionality described above.

**Comment by fhoering** [comment]
We updated to skein 0.7.1.
