### ISSUE TITLE
pex error: Unsatisfiable: Could not satisfy all requirements for mkl-fft==1.0.12:     mkl-fft==1.0.12

### ISSUE THREAD

**Issue by cmacdonald** [criteo/tf-yarn#36]
Hi,

I am trying to follow the example code at 
https://github.com/criteo/tf-yarn/blob/master/examples/linear_classifier_example.py

I get 
```
Unsatisfiable: Could not satisfy all requirements for mkl-fft==1.0.12:
    mkl-fft==1.0.12
```

Same error occurs if I run `pex mkl-fft==1.0.12` on the command line.

Any hints?

BTW: My anaconda installation is on a shared NFS path, visible to all machines. Is it therefore needed to package?

**Comment by fhoering** [comment]
On Pypi the last version for mkl-fft is 1.0.6
https://pypi.org/project/mkl-fft/#history

Pex works for this version, so it should also work with `upload_env_to_hdfs`
```
pex mkl-fft==1.0.6
```

Are you using an internal custom build hosted on another packaging server ?

**Comment by cmacdonald** [comment]
Anaconda has 1.0.13:
https://anaconda.org/conda-forge/mkl_fft/files

Craig

**Comment by fhoering** [comment]
OK, then you should use CONDA_PACKER which will use [conda-pack](https://conda.github.io/conda-pack/) to ship your environment to the cluster.

pex doesn't support conda packages.
See this [ticket](https://github.com/pantsbuild/pex/issues/627)
(https://github.com/pantsbuild/pex/issues/627)

**Comment by cmacdonald** [comment]
Fair - hence my other ticket. Can you detect Conda in the pex packer?
According to https://stackoverflow.com/questions/21282363/any-way-to-tell-if-users-python-environment-is-anaconda:
`os.path.exists(os.path.join(sys.prefix, 'conda-meta'))`

(appears to work for me on Linux, TP for Anacdonda, TN for Centos python)

**Comment by cmacdonald** [comment]
Good idea. I will test.

**Comment by fhoering** [comment]
Will close this issue. If it doesn't work please reopen.
