### ISSUE TITLE
Connect to MLFlow

### ISSUE THREAD

**Issue by jdlesage** [criteo/tf-yarn#40]
It would be nice to have tf-yarn mlflow ready. 

Forward MLFLOW_SERVER_URI and MLFLOW_RUN_ID to workers + GIT quiet variable

It will implement: https://github.com/mlflow/mlflow/issues/1732

**Comment by fhoering** [comment]
Seel mlflow example:
https://github.com/criteo/tf-yarn/blob/master/examples/mlflow_example.py

Currently it tracks some metrics about container running times, steps/second and evaluator statistics.
