### ISSUE TITLE
TensorBoard as a custom page

### ISSUE THREAD

**Issue by superbobry** [criteo/tf-yarn#6]
Add a `tensorboard` flag to the `run_on_yarn` function. If the flag is set, tf-yarn should spawn TensorBoard as a separate service (not sure how to best configure the resources, but we could reuse `task_specs` for example) and expose it as a [custom page](https://jcrist.github.io/skein/web-ui.html#custom-pages).

**Comment by fhoering** [comment]
Done with:
https://github.com/criteo/tf-yarn/commit/51475aac025bab970795624e75482f52700bfc10

Issue with registration in the skein UI is tracked here:
https://github.com/jcrist/skein/issues/128
