### ISSUE TITLE
Explore dataset caching in YARN

### ISSUE THREAD

**Issue by superbobry** [criteo/tf-yarn#7]
The Dataset API allows [caching](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#cache) the dataset shard in memory or on disk. The latter requires the user to specify a path to store the data locally. It is not clear which value should be provided when running on YARN, and if there is a value which works for both local runs and on YARN.

**Comment by jdlesage** [comment]
In my opinion, that's the application to decide if caching is important. There is this documentation to guide the choice: https://www.tensorflow.org/guide/performance/datasets
And more, this function is a part of tensorflow. I don't think any modifications are needed to run it on top of Yarn. 
I think it must be tested directly in the applications. tf-yarn is probably not the good place to do this study.

**Comment by superbobry** [comment]
My point was that tf-yarn should probably provide a way to construct a filename to be passed to `Dataset.cache`.

**Comment by jdlesage** [comment]
The way to construct the filename will be probably very dependent of the cluster. That's a nice idea, but I don't see how to integrate this into tf-yarn.
